# Generated by Django 4.2.19 on 2025-04-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentt',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
